name: Run Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js v20.16.0
        uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm exec web-ext lint

      - name: Run code formatting check
        run: pnpm exec prettier --check .
